pub use peryx_core::{
    UiArtifactRef, UiArtifactSource, UiByteAvailability, UiFile, UiManifest, UiMember, UiMemberChunk, UiProject,
    UiProjectStatus, UiProjectView, UiRelease,
};

use super::string_at;

/// One placement chip's parts: a stable css key, the visible word, and a longer hint.
///
/// A sighted reader sees the word; a pointer or screen reader gets the hint. The visible word alone
/// distinguishes each state, so the chips never lean on colour.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlacementLabel {
    pub key: &'static str,
    pub text: &'static str,
    pub hint: &'static str,
}

/// How a file's #441 source renders: where its bytes came from, intrinsic to the artifact.
#[must_use]
pub const fn file_source_label(source: UiArtifactSource) -> PlacementLabel {
    match source {
        UiArtifactSource::Hosted => PlacementLabel {
            key: "hosted",
            text: "hosted",
            hint: "Published into this instance",
        },
        UiArtifactSource::Proxy => PlacementLabel {
            key: "proxy",
            text: "proxy",
            hint: "Cached from an upstream index",
        },
        UiArtifactSource::Generated => PlacementLabel {
            key: "generated",
            text: "generated",
            hint: "Generated by this instance",
        },
    }
}

/// How a file's #441 byte availability renders: whether this instance can serve the bytes now.
#[must_use]
pub const fn byte_availability_label(availability: UiByteAvailability) -> PlacementLabel {
    match availability {
        UiByteAvailability::Local => PlacementLabel {
            key: "local",
            text: "local",
            hint: "Served from local storage",
        },
        UiByteAvailability::RemoteOnly => PlacementLabel {
            key: "remote-only",
            text: "remote-only",
            hint: "Not stored locally; available from the upstream",
        },
        UiByteAvailability::Unavailable => PlacementLabel {
            key: "unavailable",
            text: "unavailable",
            hint: "Not stored locally and no upstream to supply it",
        },
    }
}

/// Rebuild an archive listing from the inspect endpoint's JSON document.
#[must_use]
pub fn members_from_listing(value: &serde_json::Value) -> Vec<UiMember> {
    value["members"]
        .as_array()
        .into_iter()
        .flatten()
        .map(|member| UiMember {
            path: string_at(member, "path"),
            size: member["size"].as_u64().unwrap_or_default(),
            kind: member["kind"].as_str().unwrap_or("unknown").to_owned(),
            previewable: member["previewable"].as_bool().unwrap_or(false),
        })
        .collect()
}

/// The project names of one index, from its PEP 691 list document.
#[must_use]
pub fn projects_from_list(value: &serde_json::Value) -> Vec<String> {
    value["projects"]
        .as_array()
        .into_iter()
        .flatten()
        .map(|project| string_at(project, "name"))
        .collect()
}
